version: '2'
services:

  # nginx, working as a front-end proxy for uniqush
  # we need it for only allowing certain endpoints to be available
  nginx:
    build: https://github.com/PushOCCRP/watchful-nginx.git
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
#     - letsencrypt
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - ./secrets.env
    volumes:
      - "./.docker/nginx/:/etc/nginx/"                            # config
      - "./.docker/nginx/:/etc/ssl/nginx"
      - "./.docker/data/secrets/keys:/srv/data"                # dhpram and certs are here
      #- "./.docker/data/secrets/keys/live/`ls`:/srv/data/ssl/keys:ro"
      - "./.docker/data/secrets/keys/archive/:/etc/letsencrypt/archive"
      # - "./.docker/data/secrets/keys/live/$LETSENCRYPT_DOMAINS:/srv/data/ssl/keys"
      - "./.docker/data/secrets/keys/live/offline-dev.pushapp.press:/srv/data/ssl/keys:rw"
      - "./public/:/var/public/:ro"



  db:
    image: postgres:9.6
    restart: always
    volumes:
      - "./.docker/postgres:/data/postgres"
      - "./.docker/backups:/data/backups"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: always
    volumes:
      - ".:/push:cached"
      - "rails_cache:/app/tmp/cache"
      - "node_modules:/app/node_modules"
      - "packs:/app/public/packs"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - uniqush
    env_file:
      - ./secrets.env
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - proxy_images=true
    entrypoint: /push/entrypoint.sh
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  # uniqush itself
  uniqush:
      build: https://github.com/beevelop/docker-uniqush.git
      restart: always
      environment:
          # this is the default, but let's be explicit here
          UNIQUSH_DATABASE_HOST: "redis"
#          UNIQUSH_LOGFILE:       "/var/log/uniqush"
#          UNIQUSH_LOGLEVEL:      "verbose"
          UNIQUSH_GID:           "60001"
          UNIQUSH_UID:           "60001"
      depends_on:
          - redis
      volumes:
          - "./secrets:/secrets:cached"
          - "./log/uniqush:/var/log/uniqush:cached"
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"

  # the redis db server
  redis:
      image: redis
      restart: always
      volumes:
          - "./.docker/redis:/data:cached"
      command: ["redis-server", "--appendonly", "yes"]
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"

  logrotate:
    image: blacklabelops/logrotate
    restart: always
    volumes:
      - "./log:/logs"
    environment:
      - LOGS_DIRECTORIES=/logs
      - LOGROTATE_SIZE=5M
      - LOGROTATE_CRONSCHEDULE=0 0 * * * *
      - LOGROTATE_COMPRESSION=compress
      - LOGROTATE_COPIES=5

volumes:
  rails_cache:
  node_modules:
  packs:
