version: '2'
services:

  # 
  # nginx, working as a front-end proxy for uniqush
  # we need it for only allowing certain endpoints to be available
  nginx:
      image: nginx
      ports:
          - "80:80"
          - "443:443"
      depends_on:
          - web
      volumes:
          - "./.docker/nginx/:/etc/nginx/:ro"                            # config
          - "./.docker/data/secrets/:/srv/data/ssl/:ro"                # dhpram and certs are here
          - "./public/:/var/public/:ro"
  db:
    image: postgres
    volumes:
      - ./.docker/postgres:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/push
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./secrets.env
    environment:
      - RAILS_ENV=${RAILS_ENV}
    entrypoint: /push/entrypoint.sh
#    extra_hosts:                            # For dev purposes only
#      - "rise.md:213.133.100.136"
#      - "www.rise.md:213.133.100.136"


  # uniqush itself
  uniqush:
      build:
          context: docker-uniqush
      environment:
          # this is the default, but let's be explicit here
          UNIQUSH_DATABASE_HOST: "redis"
#          UNIQUSH_LOGFILE:       "/srv/logs/gurac/uniqush.log"
          UNIQUSH_LOGLEVEL:      "verbose"
          UNIQUSH_GID:           "60001"
          UNIQUSH_UID:           "60001"
      ports:
          - "9898:9898"
      depends_on:
          - redis
      volumes:
          - "./secrets:/secrets"
          #- "/srv/logs/gurac/:/srv/logs/gurac/"

  # the redis db server
  redis:
      image: redis
      volumes:
          - "./.docker/redis:/data"
      command: ["redis-server", "--appendonly", "yes"]
