version: '2'
services:

  #
  # nginx, working as a front-end proxy for uniqush
  # we need it for only allowing certain endpoints to be available
  nginx:
    build: https://github.com/PushOCCRP/watchful-nginx.git
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
#      - letsencrypt
    env_file:
      - ./secrets.env
    volumes:
      - "./.docker/nginx/:/etc/nginx/:ro"                            # config
      - "./.docker/nginx/:/etc/ssl/nginx"
      - "./.docker/data/secrets/keys/:/srv/data/:ro"                # dhpram and certs are here
      #- "./.docker/data/secrets/keys/live/`ls`:/srv/data/ssl/keys:ro"
      - "./.docker/data/secrets/keys/live/$LETSENCRYPT_DOMAINS:/srv/data/ssl/keys:ro"
      - "./.docker/data/secrets/keys:/srv/data/"
      - "./public/:/var/public/:ro"
  db:
    image: postgres
    volumes:
      - "./.docker/postgres:/data/postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/push
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - uniqush
    env_file:
      - ./secrets.env
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - proxy_images=true
    entrypoint: /push/entrypoint.sh
    tty: true
    stdin_open: true

#    extra_hosts:                            # For dev purposes only
#      - "rise.md:213.133.100.136"
#      - "www.rise.md:213.133.100.136"


  # uniqush itself
  uniqush:
      build: https://github.com/beevelop/docker-uniqush.git
      environment:
          # this is the default, but let's be explicit here
          UNIQUSH_DATABASE_HOST: "redis"
#          UNIQUSH_LOGFILE:       "/srv/logs/gurac/uniqush.log"
          UNIQUSH_LOGLEVEL:      "verbose"
          UNIQUSH_GID:           "60001"
          UNIQUSH_UID:           "60001"
      ports:
          - "9898:9898"
      depends_on:
          - redis
      volumes:
          - "./secrets:/secrets"
          #- "/srv/logs/gurac/:/srv/logs/gurac/"

  # the redis db server
  redis:
      image: redis
      volumes:
          - "./.docker/redis:/data"
      command: ["redis-server", "--appendonly", "yes"]
